<?php

/**
 * @file custom_actions.module
 * TODO: Enter file description here.
 */

// Drupal needs this blank file.

/**
 * Implements hook_action_info().
 */
function custom_actions_action_info() {
  return array(
    '_custom_actions_landing_per_role' => array(
      'label' => t('Redireciona Landing para do papel do usuário'),
      'type' => 'user',
      'configurable' => FALSE,
      'triggers' => array('any'),
    ),
  );
}

function _custom_actions_landing_per_role(&$entity, $context = array()){
	if($entity->uid == 1){
		$_GET['destination'] = 'administrator';
	}else{
		$_GET['destination'] = end($entity->roles);
	}
}